language: node_js

node_js:
  - "6.9.2"
  
before_script:
  - chmod 777 -R scriptTest.pl

script: 
  - perl scriptTest.pl

notifications:
  email: false
  
deploy:
  provider: script
  skip_cleanup: true
  script: curl -u ${DEPLOY_USER}:${DEPLOY_PASS} -X POST https://docker-api.vibioh.fr/containers/spring/ --data-binary @docker-compose.yml
  on:
    branch: docker